Feature Update: Implementation and Styling based on Zeplin Designs
Rafiduzzaman/bookstore pull request #5
Opened 2023-09-15 22:31 UTC by Rafiduzzaman

**Pull Request Description**:
This pull request encompasses the following accomplishments:
- Adherence to general requirements:
  - Ensured no linter errors.
  - Followed Gitflow for version control.
  - Documented work in a professional manner.

- HTML/CSS Accomplishments:
  - Followed the best practices for HTML & CSS.
  - Integrated missing JSX elements based on project requirements without adding extra functionality.
  - Styled the website to match Zeplin's design using the provided CSS rules.

---

**Code Changes**:
- Integrated missing JSX elements based on project requirements and Zeplin designs.
- Styled the website to match Zeplin's design using appropriate CSS rules.

2023-09-15 23:32 UTC, iambenkis requested changes
#### Hi @Rafiduzzaman 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️ Work documented professionally

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-09-15 23:32 UTC, iambenkis commented on src/index.css
> +  }
- [ ] Good job Styling your bookstore 👏. As for the page , you should make sure your design matches the design 👍. Your design does not fill all the size of the screen as in the Zeplin design , Kindly fix that 😄 

### Your design

![Capture](https://github.com/Rafiduzzaman/bookstore/assets/80458199/6682f1a1-c5ac-4741-ac45-dbc580cde093)

### Zeplin

![Capture0](https://github.com/Rafiduzzaman/bookstore/assets/80458199/c9577a2a-0e14-4489-a2f1-a8d2b87646aa)

2023-09-15 23:32 UTC, iambenkis commented on src/index.css
> +  }
- [ ] Kindly ensure that your design matches the Zeplin design to meet the requirements  👍 

### Your design

![Capture](https://github.com/Rafiduzzaman/bookstore/assets/80458199/360189c3-2846-498b-aafa-5d5811432a37)

### Zeplin design

![Capture0](https://github.com/Rafiduzzaman/bookstore/assets/80458199/7f920332-0009-4c5e-9b24-bbacb3618c62)

2023-09-15 23:32 UTC, iambenkis commented on src/index.css
> +  }
- [ ] To ensure that your design matches the Zeplin design 👍 , the alignment , the margin, the padding  etc are exactly the same as in the design template

### Your design
![Capture](https://github.com/Rafiduzzaman/bookstore/assets/80458199/4e320e96-f5ae-4627-aa66-67031c53e10a)

### Zeplin design

![Capture0](https://github.com/Rafiduzzaman/bookstore/assets/80458199/d2f9c59a-7e07-4a83-9fb1-b4c83384fc9e)

2023-09-15 23:32 UTC, iambenkis commented on src/index.css
> +    letter-spacing: normal;
- [ ] The add book section should stick to the Zeplin design , Kinldy fix that 👍 

### Your design
![Capture](https://github.com/Rafiduzzaman/bookstore/assets/80458199/37bb7b5c-8a94-4374-9d96-ce238403227f)

### Zeplin design
![Capture0](https://github.com/Rafiduzzaman/bookstore/assets/80458199/8130e98e-b557-48ef-9234-2452e26906cd)

2023-09-16 00:34 UTC, ademibowale approved these changes
Hi @Rafiduzzaman  , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️
- Use functional components✔️
- final design should match Zeplin's design (.✔️
- Descriptive commit messages ✔️ 
- Good use of Github flow ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)




- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-16 00:59 UTC, merged